# Generated by Django 4.2.16 on 2024-09-17 23:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": 'auth"."users',
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="SupabaseAuthUser",
            fields=[
                ("instance_id", models.UUIDField(blank=True, null=True)),
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("aud", models.CharField(blank=True, max_length=255, null=True)),
                ("role", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "encrypted_password",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("invited_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("confirmation_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recovery_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("recovery_sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_change_token_new",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_change",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("email_change_sent_at", models.DateTimeField(blank=True, null=True)),
                ("last_sign_in_at", models.DateTimeField(blank=True, null=True)),
                ("raw_app_meta_data", models.JSONField(blank=True, null=True)),
                ("raw_user_meta_data", models.JSONField(blank=True, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("phone", models.TextField(blank=True, null=True)),
                ("phone_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("phone_change", models.TextField(blank=True, null=True)),
                (
                    "phone_change_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("phone_change_sent_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_change_token_current",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "email_change_confirm_status",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("banned_until", models.DateTimeField(blank=True, null=True)),
                (
                    "reauthentication_token",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "reauthentication_sent_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("is_sso_user", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("is_anonymous", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "auth.users",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "managed": True,
            },
        ),
    ]
