# Generated by Django 4.2.16 on 2024-09-17 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TikTokVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tiktok_video_url", models.URLField(unique=True)),
                ("downloaded_video_url", models.URLField(blank=True, null=True)),
                ("ai_processed", models.BooleanField(default=False)),
                ("transcription", models.TextField(blank=True, null=True)),
                ("generated_caption", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
