# Generated by Django 4.2.16 on 2024-09-17 03:26

import core.models.base_model
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("General", "General"),
                            ("Technical", "Technical"),
                            ("Billing", "Billing"),
                            ("Print Orders", "Print Orders"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("question", models.CharField(max_length=255)),
                ("answer", models.TextField()),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.base_model.JSONSerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="HelpArticle",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("snippet", models.CharField(max_length=500)),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.base_model.JSONSerializableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("subject", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("Technical Issue", "Technical Issue"),
                            ("Billing", "Billing"),
                            ("Print Orders", "Print Orders"),
                            ("Other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("attachments", models.JSONField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Open", "Open"),
                            ("In Progress", "In Progress"),
                            ("Resolved", "Resolved"),
                            ("Closed", "Closed"),
                        ],
                        default="Open",
                        max_length=20,
                    ),
                ),
                ("response", models.TextField(blank=True, null=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "abstract": False,
            },
            bases=(core.models.base_model.JSONSerializableMixin, models.Model),
        ),
    ]
